### PR TITLE
Link to project docs for installation

### PR DESCRIPTION
**Pull request by tcharding**
Currently we only have OS X installation documentation in the README. Solidity maintains their own installation docs for various platforms as does Ethereum, we can use these.

Link to project docs for installation instructions.

Signed-off-by: Tobin C. Harding <me@tobin.cc>

### CODE REVIEW

**Comment by Waldz** [comment]
LGTM, but CI is failing

**Comment by tcharding** [comment]
`goimports` issue here also.  Re-trying with updated tool.

**Comment by zolia** [comment]
interesting, its probably related with this: 
>	tcharding wants to merge 1 commit into mysteriumnetwork:master from unknown repository

Do not know how to fix that. :/

**Comment by soffokl** [comment]
@zolia it was the same when repo was present. 
We need to check repo settings, but I don't have permissions for that.

**Comment by zolia** [comment]
used this procedure to resolve this issue: 

If there is a PR displaying unknown repository after the fork was deleted, and you want to resurrect that PR, simply type:

git fetch origin refs/pull/123/head:foo
substituting (if necessary) origin for the remote pointing at the target repo, 123 for the PR number, and foo for the name of the local branch you want created to point to the head of the PR.

Then you can simply git checkout foo, close the stale PR, and resubmit a new one which supersedes it.

**Comment by tadovas** [comment]
Closing this PR as copy of it was already merged

**Pull request closed without merging**
